# Generated by Django 3.2.15 on 2022-10-04 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledin',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 4)),
        ),
    ]
