# Generated by Django 3.2.15 on 2022-10-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_enrolledin_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='userSkills',
            new_name='user_skills',
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
