# Generated by Django 3.2.15 on 2022-10-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221004_0512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrolledin',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrolledin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='prerequisitcourses',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrolled_in',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_skills',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Deliverable',
        ),
        migrations.DeleteModel(
            name='EnrolledIn',
        ),
        migrations.DeleteModel(
            name='PrerequisitCourses',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
