# Generated by Django 3.2.15 on 2022-10-05 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledin',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 5)),
        ),
    ]
