# Generated by Django 3.2.15 on 2022-10-06 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_enrolledin_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverable',
            old_name='course',
            new_name='deliverable_course',
        ),
        migrations.AlterField(
            model_name='enrolledin',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 6)),
        ),
    ]
