# Generated by Django 3.2.15 on 2022-10-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20221006_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolled_in',
            field=models.ManyToManyField(related_name='courses', through='api.EnrolledIn', to='api.Course'),
        ),
    ]
