# Generated by Django 3.2.15 on 2022-10-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_student_enrolled_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_in',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', through='api.EnrolledIn', to='api.Student'),
        ),
        migrations.AlterField(
            model_name='enrolledin',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
