# Generated by Django 3.2.15 on 2022-10-06 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_course_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledin',
            old_name='user',
            new_name='student',
        ),
    ]
