# Generated by Django 3.2.15 on 2022-10-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_user_enrolledin_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user_skills',
            new_name='student_skills',
        ),
    ]
