# Generated by Django 3.2.16 on 2022-10-09 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_user_skills_student_student_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledin',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 9)),
        ),
    ]
